services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgresusr:password@db:5432/capturedcollective
      - PORT=7000
      - OPENAI-API=open-ai-token-here
      - SESSION_SECRET=your-secure-session-secret-here
      - TWILIO_ACCOUNT_SID=your-twilio-account-sid
      - TWILIO_AUTH_TOKEN=your-twilio-auth-token
      - TWILIO_PHONE_NUMBER=your-twilio-phone-number
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgresusr
      POSTGRES_PASSWORD: password
      POSTGRES_DB: capturedcollective
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
